### ISSUE TITLE
How to Push MicroServioce in PCF?

### ISSUE THREAD

**Issue by MohanBunny** [ewolff/microservice#13]
Hi,
Thanks for your post.
We have already written microservices and we would like to push it on pcf.
But we dont know how to proceed further as we are new to deploy microservices on pcf.
We just want to push a addition microservice which is written in maven(java).
i.e it includes,
**1:-EurekaServer
2:-MicroServiceForAddition
3:-DiscoveryClient**

Do we need to add manifest file to push the app,if yes then,
We have provided the manifest file which includes,
```
App name
Instances
Hostname
Memory
```
Please suggest me.
Thanks.
Mohan.V

**Comment by ewolff** [comment]
Please refer to https://docs.cloudfoundry.org/buildpacks/java/gsg-spring.html
