### ISSUE TITLE
Executing vagrant provision first

### ISSUE THREAD

**Issue by miwoe** [ewolff/microservice#15]
Hi,

I had some issues starting this example.

1st was that my vagrant VM could not connect to internet and that the trust needs an update before installation of docker was a success. (Always ended up with "Docker installation failed".

So, I have added following lines in the Vagrantfile:
```
config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
  config.vm.provision "shell", inline: "sudo apt-get update"
```

2nd was that it seems to be necessary to run 
`vagrant provision`
before
`vagrant up`

Therefore, it should be added to the ReadMe.txt. Took me some time to understand what is failing. On the other hand, I have learned something more about vagrant docker integration. :)

**Comment by ewolff** [comment]
Thanks for reporting the issue. For #10 I just tried the Vagrant setup and it did work for me. Can you make sure that the following conditions are met:
- Latest version of this project
- Latest version of Vagrant (I used 1.8.5)
- Latests ubuntu/trusty64  (I used virtualbox, 20160926.0.1). You can find them with `vagrant box list`and update it with `vagrant box update`

This issue doesn't really seem like a problem of this project, but rather of Vagrant. In fact there are issues that seem very similar like https://github.com/mitchellh/vagrant/issues/5697 .

**Comment by miwoe** [comment]
Everything up-to-date:
> ~/git/microservice/docker-vagrant:$ vagrant -v
Vagrant 1.8.6
> ~/git/microservice/docker-vagrant:$ vagrant box list
ubuntu/trusty64 (virtualbox, 20160926.0.1)

As mentioned in the referenced issue, doing "sudo apt-get update" before docker setup did it also for me.
