### ISSUE TITLE
Error on executing vagrant up

### ISSUE THREAD

**Issue by moabdi** [ewolff/microservice#19]
Hello,
Pease can u help me.
Your tuterial is interseted, I tried to execute vargant up but I alwayes get erreur.

.......
==> default: Forwarding ports...
    default: 8080 (guest) => 18080 (host) (adapter 1)
    default: 8761 (guest) => 18761 (host) (adapter 1)
    default: 8989 (guest) => 18989 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.36
    default: VirtualBox Version: 5.1
==> default: Mounting shared folders...
    default: /vagrant => D:/worktraining/architecture/microservice-master/docker-vagrant
    default: /microservice-demo => D:/worktraining/architecture/microservice-master/microservice-demo
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: docker...
==> default: Starting Docker containers...
==> default: -- Container: eureka
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

          rm -f /var/lib/vagrant/cids/8471cfc1fb670d34d41fc592fb1a3a5662ede334
          docker run --cidfile=/var/lib/vagrant/cids/8471cfc1fb670d34d41fc592fb1a3a5662ede334 -d --name eureka --restart=always -p 8761:8761 -v /microservice-demo:/microservice-demo eureka

Stdout from the command:

Stderr from the command:

Unable to find image 'eureka:latest' locally
docker: Error response from daemon: repository eureka not found: does not exist or no pull access.
See 'docker run --help'.

**Comment by ewolff** [comment]
Thanks for pointing this out. Please `git pull` to the latest code and `vagrant provision` to provision with the new software. Let me know if this does not work.

**Comment by moabdi** [comment]
![image](https://user-images.githubusercontent.com/12466761/29493781-62866456-859d-11e7-82ac-084e9b872a88.png)

I have always the problem.

**Comment by ewolff** [comment]
Please make sure you are using the latest version and then try ´vagrant
destroy´ followed by ´vagrant up´

--
Eberhard Wolff
+49 151 75004986

http://ewolff.com       Twitter: @ewolff        Skype: ebr.wolff

Continuous Delivery Buch: http://continuous-delivery-buch.de
Microservices Buch (Deutsch): http://microservices-buch.de
Microservices Book (English): http://microservices-book.com

**Comment by moabdi** [comment]
Yeah, I downloaded the latest version, I think the local images are unknowen. I think we have to copy the images after build into vertual machine to be knowen on the execution.

**Comment by moabdi** [comment]
D:\worktraining\architecture\microservice-master\docker-vagrant>vagrant -v
Vagrant 1.9.7

**Comment by ewolff** [comment]
Please try ´vagrant destroy´ before ´vagrant up´. The images are only
created in the first ´vagrant up´ execution.


Creating the images must have failed in your case. I don't see the error
message though.

You can also run ´vagrant provision´ to have the images created.

**Comment by ewolff** [comment]
Update the git repo using ´git pull´

**Comment by moabdi** [comment]
Thanks, the cammand run correctly now, but the url 127.0.0.1:port, don't work.

**Comment by moabdi** [comment]
It's Ok, it works with localhost on my machine, not with 127.0.0.1.
Thanks very much, your demo it's very hulpful.

**Comment by ewolff** [comment]
Great - thanks! 👍🙂🐺

On Aug 20, 2017 12:20, "Mostapha ABDI" <notifications@github.com> wrote:

It's Ok, it works with localhost on my machine, not with 127.0.0.1.
Thanks very much, your demo it's very hulpful.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ewolff/microservice/issues/19#issuecomment-323576131>,
or mute the thread
