### ISSUE TITLE
Could you please update readme for how to invoke the endpoints and sequences to start the services?

### ISSUE THREAD

**Issue by ghost** [ewolff/microservice#23]

**Comment by ewolff** [comment]
I am not sure what you missing. https://github.com/ewolff/microservice/blob/master/HOW-TO-RUN.md explains how to run the whole system. Afterwards http://localhost:8080/ provides access to the HTML pages of the microservices. The microservices provide a web UI.

**Comment by ewolff** [comment]
I am still not sure what needs to be done, sorry.
