### ISSUE TITLE
Pipeline with multimodules

### ISSUE THREAD

**Issue by renatojava** [ewolff/microservice#24]
Hello, 

I am seeing the repository and I have one doubt, Is correct have one repo with N modules when we are using microservice (as in the sample project)?
My doubt is because when you will create a new pipeline generally you have one repo per pipeline, and if you have N projects I don't know how to config the pipeline.
Another point would be regarding the need to check out all sources to develop.

**Comment by ewolff** [comment]
Good point! I would agree that in real life you should have a separate project in the version control and also for the build tool for each microservice. The goal is to implement a separate deployment unit. I find it easier to run the example as is so I will probably not change this. Let me know what you think!

**Comment by ewolff** [comment]
As mentioned I decided not to change this. Sorry.
