### ISSUE TITLE
Vagrant up / provision not working

### ISSUE THREAD

**Issue by mmattersdorfer** [ewolff/microservice#7]
I'm trying to run Your example, but I am getting the following error while executing the command 'vagrant up' or 'vagrant provision' - since I'm new to vagrant and docker I don't know how to fix this. I'm using Windows 7. Can You help me please?

 The command '/bin/sh -c apk add --update wget ca-certificates &&     cd /tmp &&     wget -nv "https://circle-artifacts.com/gh/andyshinn/alpine-pkg-glibc/6/artifacts/0/home/ubuntu/alpine-pkg-glibc/packages/x86_64/glibc-2.21-r2.apk"          "https://circle-artifacts.com/gh/andyshinn/alpine-pkg-glibc/6/artifacts/0/home/ubuntu/alpine-pkg-glibc/packages/x86_64/glibc-bin-2.21-r2.apk" &&     apk add --allow-untrusted glibc-2.21-r2.apk glibc-bin-2.21-r2.apk &&     /usr/glibc/usr/bin/ldconfig /lib /usr/glibc/usr/lib &&     echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf &&     wget -nv --header "Cookie: oraclelicense=accept-securebackup-cookie;"         "http://download.oracle.com/otn-pub/java/jdk/${JAVA_VERSION}u${JAVA_UPDATE}-b${JAVA_BUILD}/jdk-${JAVA_VERSION}u${JAVA_UPDATE}-linux-x64.tar.gz" &&     tar xzf "jdk-${JAVA_VERSION}u${JAVA_UPDATE}-linux-x64.tar.gz" &&     mkdir -p /usr/lib/jvm &&     mv "/tmp/jdk1.${JAVA_VERSION}.0_${JAVA_UPDATE}" "/usr/lib/jvm/java-${JAVA_VERSION}-oracle" &&     ln -s "java-${JAVA_VERSION}-oracle" $JAVA_HOME &&     ln -s $JAVA_HOME/bin/java /usr/bin/java &&     ln -s $JAVA_HOME/bin/javac /usr/bin/javac &&     rm -rf $JAVA_HOME/*src.zip &&     rm -rf $JAVA_HOME/lib/missioncontrol            $JAVA_HOME/lib/visualvm            $JAVA_HOME/lib/*javafx*            $JAVA_HOME/jre/lib/plugin.jar            $JAVA_HOME/jre/lib/ext/jfxrt.jar            $JAVA_HOME/jre/bin/javaws            $JAVA_HOME/jre/lib/javaws.jar            $JAVA_HOME/jre/lib/desktop            $JAVA_HOME/jre/plugin            $JAVA_HOME/jre/lib/deploy*            $JAVA_HOME/jre/lib/*javafx*            $JAVA_HOME/jre/lib/*jfx*            $JAVA_HOME/jre/lib/amd64/libdecora_sse.so            $JAVA_HOME/jre/lib/amd64/libprism_*.so            $JAVA_HOME/jre/lib/amd64/libfxplugins.so            $JAVA_HOME/jre/lib/amd64/libglass.so            $JAVA_HOME/jre/lib/amd64/libgstreamer-lite.so            $JAVA_HOME/jre/lib/amd64/libjavafx*.so            $JAVA_HOME/jre/lib/amd64/libjfx*.so &&     rm -rf $JAVA_HOME/jre/bin/jjs            $JAVA_HOME/jre/bin/keytool            $JAVA_HOME/jre/bin/orbd            $JAVA_HOME/jre/bin/pack200            $JAVA_HOME/jre/bin/policytool            $JAVA_HOME/jre/bin/rmid            $JAVA_HOME/jre/bin/rmiregistry            $JAVA_HOME/jre/bin/servertool            $JAVA_HOME/jre/bin/tnameserv            $JAVA_HOME/jre/bin/unpack200            $JAVA_HOME/jre/lib/ext/nashorn.jar            $JAVA_HOME/jre/lib/jfr.jar            $JAVA_HOME/jre/lib/jfr            $JAVA_HOME/jre/lib/oblique-fonts &&     apk del wget ca-certificates &&     rm /tmp/* /var/cache/apk/*' returned a non-zero code: 4

**Comment by mmattersdorfer** [comment]
I've found a solution - there is an update of the java-dockerfile:

https://hub.docker.com/r/frolvlad/alpine-oraclejdk8/

If you use the code from the follwoing Github-Link for the Dockerfile in the directory 'microservice\docker-vagrant\java\' it works.

https://github.com/frol/docker-alpine-oraclejdk8/blob/master/Dockerfile

Perhaps You can update the code in this project.

**Comment by ewolff** [comment]
Thanks a lot - I fixed it as suggested :-)
